### ISSUE TITLE
As a medical professional, I would like to able to choose between the imperial and metric system of measurement and other preferences; these changes should persist in every subsequent use of the application

### ISSUE THREAD

**Issue by RohanIyengar** [BPForEveryone/BloodPressureForEveryone#10]
# Story/Task Details
- [x] Option to choose measurement system
- [x] Choice of measurement(s) persist

# Acceptance Scenarios
- Given: the medical professional application has been opened.
- When: a medical professional selects a system of measurement.
- Then: all subsequent interactions with the application should use the selected measurement system (ie. selecting patient physical characteristics)

# Done Done Criteria
Code has been implemented such that it persists and is easy to extend as new pages are created.

**Comment by MiningMarsh** [comment]
Finished.
