### ISSUE TITLE
As a caregiver, I would like to create a patient and add his/her basic information so that I can easily track his/her blood pressure history

### ISSUE THREAD

**Issue by RohanIyengar** [BPForEveryone/BloodPressureForEveryone#11]
# Story/Task Details
- [x] New screen to create patient exits
- [x] Patients can be created and persist when using the app
- [x] Connect UI View to the persisting patient

# Acceptance Scenarios
- Given: the BP for everyone application has been opened.
- When: an everyday user chooses to add a new patient to track and enters the patient's relevant physical information.
- Then: that patient can be selected in the application to view/add to the patient's history

# Done Done Criteria
Patient information should persist in at least a session of the application for this sprint. Preferably this data should be stored internally in the application to be recalled in subsequent uses of the application. Unit tests should be included if persistence is achieved.

**Comment by MiningMarsh** [comment]
This has been completed, I just pushed last fixes. Moving to closed
