### ISSUE TITLE
As a caregiver, I would like to edit an existing patient's information to be tracked so that I can more accurately measure and log their blood pressure

### ISSUE THREAD

**Issue by RohanIyengar** [BPForEveryone/BloodPressureForEveryone#12]
# Story/Task Details
- [x] Edit button when viewing patient information
- [x] Changes should persist to that patient

# Acceptance Scenarios
- Given: the BP for everyone application has been opened.
- When: an everyday user chooses chooses to edit a patient when viewing detailed history for a particular patient.
- Then: any changes the caregiver makes to that patient should be reflected whenever that patient is selected next.

# Done Done Criteria
Patient information should persist after being edited recalled in subsequent use of the application. Unit tests should be included if persistence is achieved.

**Comment by MiningMarsh** [comment]
Adding patients is finished, and they persist. Editing is not yet done.

**Comment by MiningMarsh** [comment]
Finishing/Finished.
