### ISSUE TITLE
As a caregiver, I would like to log a patient's blood pressure readings so that I may receive information regarding their reading and review the reading later

### ISSUE THREAD

**Issue by RohanIyengar** [BPForEveryone/BloodPressureForEveryone#13]
# Story/Task Details
- [x] New screen to add a blood pressure reading to a patient exists
- [x] Confirmation when a reading is entered
- [x] Reading will persist and be view-able on the patient information page.

# Acceptance Scenarios
- Given: the BP for everyone application has been opened.
- When: an everyday user chooses to add a blood pressure reading to a patient to track and enters the reading.
- Then: that reading will be view-able in the the patient's history

# Done Done Criteria
Patient readings persist in at least a session of the application for this sprint. Preferably this data should be stored internally in the application to be recalled in subsequent uses of the application. Unit tests should be included if persistence is achieved.

**Comment by MiningMarsh** [comment]
Finishing/Finished.
