### ISSUE TITLE
As a caregiver, I would like to able to choose between the imperial and metric system of measurement and other preferences; these changes should persist in every subsequent use of the application

### ISSUE THREAD

**Issue by RohanIyengar** [BPForEveryone/BloodPressureForEveryone#14]
# Story/Task Details
- [x] Option to choose measurement system
- [x] Choice of measurement(s) persist

# Acceptance Scenarios
- Given: the BP for Everyone application has been opened.
- When: a caregiver selects a system of measurement.
- Then: all subsequent interactions with the application should use the selected measurement system (ie. selecting patient physical characteristics)

# Done Done Criteria
Code has been implemented such that it persists and is easy to extend as new pages are created.

**Comment by blackstone13** [comment]
We should probably default this to the system local, then let the user override that if he wants
how to check here -> https://stackoverflow.com/questions/7413144/how-do-i-know-which-is-the-default-measure-system-imperial-or-metric-on-ios

**Comment by tlight6** [comment]
Yeah, that sounds good.

**Comment by MiningMarsh** [comment]
I verified this is finished and working.
