### ISSUE TITLE
Articles on correct ways to measure BP - BP For Professionals

### ISSUE THREAD

**Issue by RohanIyengar** [BPForEveryone/BloodPressureForEveryone#39]
# Story/Task Details
- [ ] Articles are put  up on the app that show common  mistakes made taken blood pressures.

# Acceptance Scenarios
- Given: the BP for Professioanls application has been opened and the user has clicked the more information page that redirects to articles.
- When: the user looks at this page.
- Then: the user sees articles that detail common mistakes made taking BP readings and can click on the articles to read them.

# Done Done Criteria
Articles can be read from the BP For Professionals Application.

**Comment by tlight6** [comment]
Articles researched and linked.
