### ISSUE TITLE
Articles on how to measure BP - BP For Everyone

### ISSUE THREAD

**Issue by RohanIyengar** [BPForEveryone/BloodPressureForEveryone#41]
# Story/Task Details
- [x] Articles are put up to show how to take blood pressure measurements for a patient.

# Acceptance Scenarios
- Given: the BP for Everyone application has been opened and the user has clicked the more information page that redirects to articles.
- When: the user looks at this page.
- Then: the user sees articles that detail how to measure blood pressure correctly and common mistakes.

# Done Done Criteria
Articles can be read from the BP For Everyone Application.

**Comment by blackstone13** [comment]
Reliable resources found and linked
