### ISSUE TITLE
Articles on how to manage BP and lifestyle - BP For Everyone

### ISSUE THREAD

**Issue by RohanIyengar** [BPForEveryone/BloodPressureForEveryone#42]
# Story/Task Details
- [x] Articles are put up to show how to live a healthy lifestyle and BP.

# Acceptance Scenarios
- Given: the BP for Everyone application has been opened and the user has clicked the more information page that redirects to articles.
- When: the user looks at this page.
- Then: the user sees articles that detail how to live a healthy lifestyle and manage BP through life choices.

# Done Done Criteria
Articles can be read from the BP For Everyone Application.

**Comment by blackstone13** [comment]
articles researched and linked
