### ISSUE TITLE
Create Artistic Logo and Title Page

### ISSUE THREAD

**Issue by RohanIyengar** [BPForEveryone/BloodPressureForEveryone#7]
# Story/Task Details

- [x] Logo Completed
- [x] Title Page Completed

# Done Done Criteria
The title page and logo have been ok'ed by all team members and incorporated in the app.

**Comment by a-human-bean** [comment]
Finished the initial versions of App Icons and Launch Images (for BPForProfessional) for Sprint 2. Once minor fixes to the Assets Catalog will allow, I can target one set if Launch Images for BPForEveryone, and another set for BPForProfessionals. Designs will be continuously improved over the course of the project.
