### ISSUE TITLE
Try Apple VM with XCode/Swift

### ISSUE THREAD

**Issue by RohanIyengar** [BPForEveryone/BloodPressureForEveryone#8]
# Story/Task Details
- [x] Rohan
- [x] Chris
- [x] Joshua
- [x] Andrew
- [x] Jacob

# Acceptance Scenarios
- Given: each team member has access to the VM and Virtualbox.
- When: each team member opens the virtual machine.
- Then: the team member can develop without lag and test iOS applications they develop.

# Done Done Criteria
Each team member is comfortable with the development environment setup and oks with a comment and an acknowledgement through the check box.

**Comment by tlight6** [comment]
I'm comfortable with the development environment setup.

**Comment by blackstone13** [comment]
This environment works well for me.

**Comment by MiningMarsh** [comment]
Ditto.

**Comment by RohanIyengar** [comment]
After a bit of troubleshooting, I'm comfortable with the development environment.
